spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:
              - openid
              - email
              - profile

springdoc:
  swagger-ui:
    oauth:
      client-id:
      client-secret:
      scope:
        - openid
        - email
        - profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
