db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url:  postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    second: 423
    third.value: third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring:
  profiles:
    active: prod
 # mvc:
 #   view:
 #     prefix: /WEB-INF/jsp
 #     suffix: .jsp
 #   format:
 #     date: iso #yyyy-MM-dd
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_spr
    username: postgres
    password: 2wsx2WSX
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false


#  config:
#    activate:
#      on-profile: prod

server:
  error:
    whitelabel:
      enabled: false
    path: /error

logging:
  level:
    root: info
    com.msp.spring: info
  file:
    name: spring.log
    path: /
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} : %msg%n"