db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url:  postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    second: 423
    third.value: third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

logging:
  level:
    root: info
    com.msp.spring: info
  file:
    name: spring.log
    path: /
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} : %msg%n"